const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
    primaryLight: "#D6798F",
    primary: "#F6465D",
    faintPrimary: "#D5EED6",
    tintPrimary: "#F0FDF4",
    background: "#F8F8F8",
    success: "#22C55E",
    successChart: "#2EBD85",
    tintSuccess: "#F0FDF4",
    secondary: "#090A1C",
    textDark: "#191A1C",
    text: "#fff",
    textDisable: "#B6B6B6",
    textPrimary: "#111827",
    tintText: "#FFFBFB",
    lightColor: "#979797",
    lightText: "#D9D9D9",
    greyText: "#9CA3AF",
    lightGrey: "#E6E9EB",
    pendingYellow: "#F7931A",
    blue: "#216CDA",
    orange: "#FF6D3B",
    indigo: "#797FD6",
    natureBlue: "#83CED5",
    borderColor: "#363E4E",
    border: "#D1D5DB",
    disabled: "#9BA8AF",
    errorRed: '#FF3C3C',
    tintRed: "#FDEFE7",

    light: {
        text: '#000',
        background: '#fff',
        tint: tintColorLight,
        btn: "#111827",
        tabIconDefault: '#ccc',
        tabIconSelected: tintColorLight,
    },
    dark: {
        text: '#fff',
        background: '#000',
        btn: "#111827",
        tint: tintColorDark,
        tabIconDefault: '#ccc',
        tabIconSelected: tintColorDark,
    },
};
