name: Deployment

on:
  push:
    branches:
      production

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install

      - name: Deploy to the server
        run: |
          sudo apt-get install sshpass
          sshpass -p Delta2022Digital ssh -v root@159.65.227.152 "cd /var/www/html && git pull"
